### ISSUE TITLE
Crash on interaction with Sequencer

### ISSUE THREAD

**Issue by Gegy** [dazsim/ModJam-5#1]
Interacted with one of the buttons on the sequencer and got this crash:
https://pastebin.com/SzABdAtE

**Comment by dazsim** [comment]
Did you click one of the BPM +/- buttons or one of the bank switching buttons by any chance? I've just pushed some sanity checking we missed to the github.  As soon as AtomicBlom is able to he update.

**Comment by Gegy** [comment]
It was one of the bank switching buttons, I believe. (I was mostly just pressing random stuff, trying to figure it out :P)

**Comment by dazsim** [comment]
This has been fixed in the latest bug fix update.  Thanks for reporting 👍
